version: '3.8'
services:
  duck-gen-be:
    build: .
    container_name: duck-gen-be
    restart: always
    ports:
      - '80:8081'
    env_file:
      - .env
    volumes:
      - /home/balint/duck-gen/data:/data

volumes:
  data:
    name: data
