version: '3.8'
services:
  duck-gen-be:
    build: .
    container_name: duck-gen-be
    restart: always
    ports:
      - '8081:80'
    env_file:
      - .env
    volumes:
      - /data:/home/balint/duck-gen/data

volumes:
  data:
    name: data
